title: <p align="center"> Duc-Nhat Luong </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/Resume_Nhat.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/duc-nhat-luong-02058617b/">LinkedIn</a> |
  <a href="https://github.com/ducnhat-luong">GitHub</a> |
  <a href="https://scholar.google.com/citations?user=Jj6xszMAAAAJ&hl=vi">GoogleScholar</a>
  </p>
  
  <p align="justify">
  I am pursing PhD degree in Systems and Control Engineering at Engineering School, Tokyo Institute of Technology, Japan.
  <br><br>
  I am conducting research in chemical plume tracing robot where I use Reinforcement Learning and related AI technologies 
  for the tasks of path and motion planning.
  <br><br>
  </p>

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true


theme: jekyll-theme-minimal
google_analytics: G-BWJCHETH8X # Google Analytics tracking ID