title: <p align="center"> Duc-Nhat Luong </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/Resume_Nhat.pdf.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/duc-nhat-luong-02058617b/">LinkedIn</a> |
  <a href="https://github.com/ducnhat-luong">GitHub</a> |
  <a href="https://scholar.google.com/citations?user=Jj6xszMAAAAJ&hl=vi">Google Scholar</a>
  </p>
  
  <p align="justify">
  I am pursing PhD degree in Systems and Control Engineering at Engineering School, Tokyo Institute of Technology, Japan.
  <br><br>
  I am conducting research in chemical plume tracing robot where I use Reinforcement Learning and related AI technologies 
  for the tasks of path and motion planning.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-BWJCHETH8X # Google Analytics tracking ID
